### ISSUE TITLE
no dejes codigo comentado

### ISSUE THREAD

**Issue by JoTerrance** [mpl96/ExamenServlet#26]
/*
	private void closeCon(Connection conn) {
		try {
		    if (conn!= null)
		        conn.close();
		} catch (SQLException se) {
		    se.printStackTrace();
		} 
	}
	
	private void closeStm(Connection conn, Statement stmt) {
		try {
		    if (stmt!=null)
		        conn.close();
		} catch (SQLException se) {
			se.printStackTrace();
		} 
	}
	*/

**Comment by mpl96** [comment]
perdon, se me olvido eliminarlo
